#impot pandas

In [16]:
import pandas as pb

data = pb.read_csv('./water_potability.csv')

data

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
...,...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,47580.991603,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1
3272,7.808856,193.553212,17329.802160,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1
3273,9.419510,175.762646,33155.578218,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1
3274,5.126763,230.603758,11983.869376,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1
3275,7.874671,195.102299,17404.177061,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1

In [15]:
from sklearn.preprocessing import StandardScaler

potability = data['Potability']
features = data.drop('Potability',axis=1)
target = data['Potability']

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)
print(features)
scaled_features

            ph    Hardness        Solids  Chloramines     Sulfate  \
0          NaN  204.890455  20791.318981     7.300212  368.516441
1     3.716080  129.422921  18630.057858     6.635246         NaN
2     8.099124  224.236259  19909.541732     9.275884         NaN
3     8.316766  214.373394  22018.417441     8.059332  356.886136
4     9.092223  181.101509  17978.986339     6.546600  310.135738
...        ...         ...           ...          ...         ...
3271  4.668102  193.681735  47580.991603     7.166639  359.948574
3272  7.808856  193.553212  17329.802160     8.061362         NaN
3273  9.419510  175.762646  33155.578218     7.350233         NaN
3274  5.126763  230.603758  11983.869376     6.303357         NaN
3275  7.874671  195.102299  17404.177061     7.509306         NaN

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity
0       564.308654       10.379783        86.990970   2.963135
1       592.885359       15.180013        56.329076   4.500656
2       418.606213       16.868637        66.420093   3.055934
3       363.266516       18.436524       100.341674   4.628771
4       398.410813       11.558279        31.997993   4.075075
...            ...             ...              ...        ...
3271    526.424171       13.894419        66.687695   4.435821
3272    392.449580       19.903225              NaN   2.798243
3273    432.044783       11.039070        69.845400   3.298875
3274    402.883113       11.168946        77.488213   4.708658
3275    327.459760       16.140368        78.698446   2.309149

[3276 rows x 9 columns]

array([[            nan,  2.59194711e-01, -1.39470871e-01, ...,
        -1.18065057e+00,  1.27344509e+00, -1.28629758e+00],
       [-2.11081821e+00, -2.03641367e+00, -3.85986650e-01, ...,
         2.70597240e-01, -6.22493246e-01,  6.84217891e-01],
       [ 6.38838417e-01,  8.47664833e-01, -2.40047337e-01, ...,
         7.81116857e-01,  1.47161514e-03, -1.16736546e+00],
       ...,
       [ 1.46716877e+00, -6.26829230e-01,  1.27080989e+00, ...,
        -9.81329234e-01,  2.13271066e-01, -8.56006782e-01],
       [-1.22584116e+00,  1.04135450e+00, -1.14405809e+00, ...,
        -9.42063817e-01,  6.85854453e-01,  9.50797383e-01],
       [ 4.98030294e-01, -3.85462310e-02, -5.25811937e-01, ...,
         5.60940070e-01,  7.60687650e-01, -2.12445866e+00]])

In [ ]:
import termios
import sys
oldval = termios.tcgetattr(sys.stdin)
print(oldval)

error: (25, 'Inappropriate ioctl for device')